### ISSUE TITLE
readme documentation 

### ISSUE THREAD

**Issue by ignatandrei** [hsu-net/source-generators#1]
THe readme from documentation does not point to right folder

For example, https://github.com/hsu-net/source-generators/blob/dev/src/Hsu.Sg.Sync/README.md 

Also, could you give examples on what the Proxy is generating and its use ?

( I want to add to my opinionated list of RSCG, https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG )

**Comment by seayxu** [comment]
Updated `README.md`
